# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  google_maps_api_key: AIzaSyDB8T7JCUe1rtBJfQ2Fh079Do6OOWrPdEM

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58b8925c283fd1227137795f4d5d598cdd87ba4623f51493cce731f7d3f04682d871a2b9af667a756f1cda2854d5cb1ec7fa5a6abdd9e9b63cfb791f2b250bb0

test:
  secret_key_base: d9eecefee78d665750ee13f07a8841ca6f8953f0c31bed34ad8f9cf7c73608c6620c5dab3f4450dc0197cdddc7926ceb5553f268a26ff55190870ad3911ec2ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
